### PR TITLE
[INTERNAL] Adopt REUSE Specification 3.0

### PR DESCRIPTION
**Pull request by RandomByte**
See https://reuse.software/spec/

The MIT licensed deploy/deploy.sh mentioned in LICENSE.txt was actually
never part of this repository but of the ui5-tooling.

### CODE REVIEW

**Comment by RandomByte** [comment]
The following files contain odd copyright headers:

- src/util/APIInfo.ts
- test/amdCleanup/jsdocDeclare.expected.js
- test/amdCleanup/jsdocDeclare.js


The reuse tool generates duplicate copyright texts in those cases (command `reuse spdx`):

```
FileName: ./src/util/APIInfo.ts
SPDXID: SPDXRef-fef78d1ade7779d09545231db476bb72
FileChecksum: SHA1: e67ba62ded3cd90821a11764e1ef772331880572
LicenseConcluded: NOASSERTION
LicenseInfoInFile: Apache-2.0
FileCopyrightText: <text>2018-2020 SAP SE or an SAP affiliate company and ui5-migration contributors
Copyright 2009-2016 SAP SE or an SAP affiliate company.</text>
```

```
FileName: ./test/amdCleanup/jsdocDeclare.expected.js
SPDXID: SPDXRef-d4ea88e2859c4b2a430daa2909710458
FileChecksum: SHA1: bf25d98857137437b6532d5724943526455b79ac
LicenseConcluded: NOASSERTION
LicenseInfoInFile: Apache-2.0
FileCopyrightText: <text>2018-2020 SAP SE or an SAP affiliate company and ui5-migration contributors
Copyright 2013-2015 SAP SE. All rights reserved</text>
```

```
FileName: ./test/amdCleanup/jsdocDeclare.js
SPDXID: SPDXRef-3314644bbfbb941cb8831bcc2ef88d7d
FileChecksum: SHA1: c931d757c211a8402e4cf7be458a26f0aaae210f
LicenseConcluded: NOASSERTION
LicenseInfoInFile: Apache-2.0
FileCopyrightText: <text>2018-2020 SAP SE or an SAP affiliate company and ui5-migration contributors
Copyright 2013-2015 SAP SE. All rights reserved</text>
```

**Comment by RandomByte** [comment]
Talked to Tobias, he said APIInfo.ts originated from OpenUI5. Therefore added to dep5. He also stated that the copyright comments from the test files can be removed.

**Comment by RandomByte** [comment]
Maybe APIInfo.ts has not been part of OpenUI5 after all. Needs to be clarified by @tobiasso85

**Comment by RandomByte** [comment]
Removed the copyright header from APIInfo.ts. It was never part of the OpenUI5 project

**Comment by RandomByte** [comment]
> Remove
> `docs/SAP Corporate Contributor License Agreement.pdf`

Same in ui5-tooling

**Comment by RandomByte** [comment]
> > Remove
> > `docs/SAP Corporate Contributor License Agreement.pdf`
> 
> Same in ui5-tooling

Done in both repos

**Review by tobiasso85 — APPROVED** [review]
LGTM

**Pull request merged**
